### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by tmheath** [elastic/go-windows#25]
pkg.go.dev has a single function from this package documented, why? Where would I find relevant documentation?

**Comment by andrewkroh** [comment]
Choose windows as the rendering.

![IMG_0477](https://github.com/elastic/go-windows/assets/4565752/2cf39123-5550-4866-9aa4-46ee319a28bf)

**Comment by tmheath** [comment]
Thank you for answering this nonsense question.
:)
