### ISSUE TITLE
_GetNativeSystemInfo fails on 64-bit Windows

### ISSUE THREAD

**Issue by strawgate** [elastic/go-windows#3]
From: https://github.com/elastic/beats/issues/7715

https://github.com/elastic/go-windows/blob/5d078fa9943c7549875ad32ed0f5cc0efa9546e1/zsyscall_windows.go#L52-L62

On 64-bit windows when compiled as 64-bit Go, r1 gets set to 0 which then causes the logic here to proceed into an error state and return syscall.EINVAL (which gets printed as "invalid argument").

On 32-bit windows (or 64-bit windows compiled with 32-bit Go) , r1 gets set to 262144 which is 0x400000 which then returns successfully.

This syscall does not provide a return code per: https://msdn.microsoft.com/en-us/library/windows/desktop/ms724340(v=vs.85).aspx -- i might be misunderstanding the semantics of GO syscalls but I think checking that r1 == 0 is incorrect here. If that's the case then why does it return 0x400000 on x86....

**Comment by strawgate** [comment]
Something like....

```
func _GetNativeSystemInfo(systemInfo *SystemInfo) (err error) {
	r1, _, e1 := syscall.Syscall(procGetNativeSystemInfo.Addr(), 1, uintptr(unsafe.Pointer(systemInfo)), 0, 0)

	if e1 != 0 {
		err = errnoErr(e1)
	}

	return
}
```

**Comment by andrewkroh** [comment]
The method is generated based on the declaration at:

https://github.com/elastic/go-windows/blob/5d078fa9943c7549875ad32ed0f5cc0efa9546e1/kernel32.go#L32:9

Invoking `go generate` causes the code to be updated.



In the stdlib methods that do not return a value omit the `(err error)` return. So I think that's what needs to be done here. https://github.com/golang/go/blob/c1e1e882d2a1e474e21bc44edf26e3fb5ab87ebc/src/syscall/syscall_windows.go#L217

`//sys   _GetNativeSystemInfo(systemInfo *SystemInfo) = kernel32.GetNativeSystemInfo`

**Comment by andrewkroh** [comment]
@strawgate Would you like to contribute the fix?
